name: Esteira de Integracao Continua

on:
  push:
    branches: [ "main" ]

jobs:
  pipeline-de-testes:
    runs-on: ubuntu-latest
    steps:
    - name: Copiando o codigo para o servidor
      uses: actions/checkout@v4

    - name: Instalando o Python no servidor
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Instalando as Dependencias
      run: pip install -r requirements.txt

    - name: Executando os Testes Automatizados
      run: pytest